version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: rand
      POSTGRES_USER: rskdafa
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  prisma-data:
